### ISSUE TITLE
Provider review

### ISSUE THREAD

**Issue by catsby** [scshitole/terraform-provider-bigip#2]
Hello! 

My name is Clint, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and have some initial feedback on the current state. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the git commit 8c7e41d593f6715fa6e21c281d915b719f994c39 .

- [ ] Please clean up the root directory of example files and the .terraform directory. The .terraform directory should be added to a .gitignore file. There are other files such as `1`, `~`, `README.md.swp`, a `terraform-provider-bigip` file that appears to be a binary, and `statefile` that need to be removed. In the `bigip` folder there appear to be backup files with `.goback` extensions that should be removed. If there are examples that should be included please move them to an `examples` directory and ensure they have a `.tf` file extension.
- [ ] Please rename the `CHANGES.md` file to `CHANGELOG.md`
- [ ] The building and installing instructions need to be updated (including the Makefile) to reflect modern Terraform. Many of the steps therein are not required. See the AWS Makefile for a guide 
- [ ] Installation should be changed to encourage users to download and compile/install via the makefile, instead of downloading a binary from another GitHub organization. Understandably the instructions may not account for the newly desired way of using the provider, from within terraform itself and pulled from releases.hashicorp.com
- [ ] There is no website directory. Please see the AWS provider as an example for the website structure and contents. The Provider and each resource / data source need to be documented in a directory `website`:. https://github.com/terraform-providers/terraform-provider-aws/tree/master/website 
- [ ] I’m unable to compile the provider. I’ve attemted to use make commands but I’m getting errors. The Makefile is a great convenience utility, however `go build` should work as well.
- [ ] Inadequate test coverage. Only 9 of the 41 files contained in the `bigip` implementation files are test files. Each resource and data source should have companion test file. 

That’s all for the initial first pass. If you believe I’ve misstated something please let me know! 

Cheers,
Clint

**Comment by scshitole** [comment]
Hi Clint,
Thank you very much for feedback, this is the old repo which you are
looking at, I have created a new Repo at
https://github.com/f5devcentral/terraform-provider-f5
and this one I have filled in the HashiCorp form, But I agree with what all
you have mentioned I will fix the same for the new Repo which I have
pointed out.
Appreciate your help
Thanks
Sanjay

**Comment by scshitole** [comment]
Hi Clint,
I am fixing these issues meanwhile I am facing a issue where when I run a
test with the latest repo I am getting panic: runtime error: invalid memory
address. My old repo tests were running fine with Terraform 8.1. Is there
something needs to be done with the 10.X on the vendor side.

please see below with new repo 10.X

============

SJC-ML-SHITOLE:terraform-provider-f5 shitole$ BIGIP_HOST=10.192.74.73
BIGIP_USER=admin BIGIP_PASSWORD=admin  make testacc

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

=== RUN   TestProvider

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

2017/10/02 13:49:15 Resource schema

--- PASS: TestProvider (0.00s)

=== RUN   TestBigipLtmIRule_create

--- PASS: TestBigipLtmIRule_create (0.84s)

=== RUN   TestBigipLtmIRule_import

--- FAIL: TestBigipLtmIRule_import (0.00s)

panic: runtime error: invalid memory address or nil pointer dereference
[recovered]

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x15fef27]


goroutine 274 [running]:

testing.tRunner.func1(0xc42050a0f0)

/usr/local/Cellar/go/1.9/libexec/src/testing/testing.go:711 +0x2d2

panic(0x170b400, 0x1bfa8d0)

/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283

github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource.testResource(0xc420017100,
0x11, 0x0, 0xc42018c240, 0x8f, 0xc4203968c0, 0x0, 0x0, 0x0, 0x0, ...)

/Users/shitole/work/src/
github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource/testing.go:737
+0x37

github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource.testStepImportState(0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

/Users/shitole/work/src/
github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource/testing_import_state.go:30
+0x1452

github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource.Test(0x1bccae0,
0xc42050a0f0, 0x0, 0xc4201bf940, 0xc4201bb260, 0x0, 0x0, 0x1806020,
0xc4203020b0, 0x1, ...)

/Users/shitole/work/src/
github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource/testing.go:440
+0x535

github.com/terraform-provider-f5/bigip.TestBigipLtmIRule_import(0xc42050a0f0)

/Users/shitole/work/src/
github.com/terraform-provider-f5/bigip/resource_bigip_ltm_irule_test.go:42
+0x241

testing.tRunner(0xc42050a0f0, 0x1805ae8)

/usr/local/Cellar/go/1.9/libexec/src/testing/testing.go:746 +0xd0

created by testing.(*T).Run

/usr/local/Cellar/go/1.9/libexec/src/testing/testing.go:789 +0x2de

exit status 2

FAIL github.com/terraform-provider-f5/bigip 3.588s

make: *** [testacc] Error 1

SJC-ML-SHITOLE:terraform-provider-f5 shitole$

SJC-ML-SHITOLE:terraform-provider-f5 shitole$



=============with Old repo 8.1=============


SJC-ML-SHITOLE:terraform-provider-bigip shitole$ export GOPATH=$HOME/dev

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$ pwd

/Users/shitole/dev/src/github.com/terraform-provider-bigip

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

SJC-ML-SHITOLE:terraform-provider-bigip shitole$ BIGIP_HOST=10.192.74.73
BIGIP_USER=admin BIGIP_PASSWORD=admin  make testacc

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

=== RUN   TestProvider

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

2017/10/02 13:56:44 Resource schema

--- PASS: TestProvider (0.00s)

=== RUN   TestBigipLtmIRule_create

--- PASS: TestBigipLtmIRule_create (0.56s)

=== RUN   TestBigipLtmIRule_import

--- PASS: TestBigipLtmIRule_import (3.97s)

=== RUN   TestBigipLtmMonitor_create

--- PASS: TestBigipLtmMonitor_create (4.22s)

=== RUN   TestBigipLtmMonitor_import

--- PASS: TestBigipLtmMonitor_import (4.00s)

=== RUN   TestBigipLtmNode_create

--- PASS: TestBigipLtmNode_create (3.99s)

=== RUN   TestBigipLtmNode_import

--- PASS: TestBigipLtmNode_import (3.99s)

=== RUN   TestBigipLtmPolicy_create

--- FAIL: TestBigipLtmPolicy_create (0.00s)

testing.go:264: Step 0 error: Configuration is invalid.

Warnings: []string(nil)

Errors: []string{"bigip_ltm_policy.test-policy: rule.0.condition.0: invalid
or unknown key: httpUri", "bigip_ltm_policy.test-policy:
rule.0.condition.0: invalid or unknown key: startsWith",
"bigip_ltm_policy.test-policy: rule.0.condition.1: invalid or unknown key:
httpMethod"}

=== RUN   TestBigipLtmPolicy_import

--- FAIL: TestBigipLtmPolicy_import (0.00s)

testing.go:264: Step 0 error: Configuration is invalid.

Warnings: []string(nil)

Errors: []string{"bigip_ltm_policy.test-policy: rule.0.condition.0: invalid
or unknown key: httpUri", "bigip_ltm_policy.test-policy:
rule.0.condition.0: invalid or unknown key: startsWith",
"bigip_ltm_policy.test-policy: rule.0.condition.1: invalid or unknown key:
httpMethod"}

=== RUN   TestBigipLtmPool_create

--- PASS: TestBigipLtmPool_create (3.91s)

=== RUN   TestBigipLtmPool_import

--- PASS: TestBigipLtmPool_import (3.99s)

=== RUN   TestBigipLtmVA_create

--- PASS: TestBigipLtmVA_create (3.97s)

=== RUN   TestBigipLtmVA_import

--- PASS: TestBigipLtmVA_import (0.60s)

=== RUN   TestBigipLtmVS_create

--- FAIL: TestBigipLtmVS_create (0.01s)

testing.go:264: Step 0 error: Configuration is invalid.

Warnings: []string(nil)

Errors: []string{"bigip_ltm_policy.test-policy: rule.0.condition.0: invalid
or unknown key: httpUri", "bigip_ltm_policy.test-policy:
rule.0.condition.0: invalid or unknown key: startsWith",
"bigip_ltm_policy.test-policy: rule.0.condition.1: invalid or unknown key:
httpMethod"}

=== RUN   TestBigipLtmVS_import

--- FAIL: TestBigipLtmVS_import (0.00s)

testing.go:264: Step 0 error: Configuration is invalid.

Warnings: []string(nil)

Errors: []string{"bigip_ltm_policy.test-policy: rule.0.condition.0: invalid
or unknown key: httpUri", "bigip_ltm_policy.test-policy:
rule.0.condition.0: invalid or unknown key: startsWith",
"bigip_ltm_policy.test-policy: rule.0.condition.1: invalid or unknown key:
httpMethod"}

=== RUN   TestValidStringValue

--- PASS: TestValidStringValue (0.00s)

=== RUN   TestInvalidStringValue

--- PASS: TestInvalidStringValue (0.00s)

=== RUN   TestF5NameString

--- PASS: TestF5NameString (0.00s)

=== RUN   TestF5NameSet

--- PASS: TestF5NameSet (0.00s)

=== RUN   TestF5NameList

--- PASS: TestF5NameList (0.00s)

FAIL

exit status 1

FAIL github.com/terraform-provider-bigip/bigip 33.320s

make: *** [testacc] Error 1

SJC-ML-SHITOLE:terraform-provider-bigip shitole$

**Comment by scshitole** [comment]
Thanks Clint, No worries I fixed the issue.
Yes we need to focus only on  https://github.com/f5devcentral/terraform-
provider-f5
you can see that I have made changes on this repo, created documentation,
removed the binary which was showing up, also currently I am adding more
test resources, will keep you update.

**Comment by catsby** [comment]
OK, I've opened up https://github.com/f5devcentral/terraform-provider-f5/issues/1 to track there
